version: '3.3'
services:
  haproxy:
    image: haproxytech/haproxy-ubuntu:2.7
    volumes:
      - "./configs/haproxy.cfg:/etc/haproxy/haproxy.cfg"
    ports:
      - "52001:52001"
      - "52005:52005"
    expose:
      # Opens port 3306 on the container
      - '52001'
      - '52005'
  mysql_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
  mssql_db:
    image: mcr.microsoft.com/azure-sql-edge
    restart: always
    cap_add:
      - SYS_PTRACE
    environment:
      ACCEPT_EULA: '1'
      MSSQL_SA_PASSWORD: 'StrongPassword123'
    ports:
      - '1433:1433'
    expose:
      - '1433'
